'use client'
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { Toaster } from "sonner";
import { UpdateCartContext } from "./_context/UpdateCartContext";
// import { usePathname } from "next/navigation";
import { useState } from "react";
import { PayPalScriptProvider } from "@paypal/react-paypal-js";

const outfit = Outfit({ subsets: ["latin"] });

// export const metadata = {
//   title: "Online Grocery App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // const params=usePathname();
  const [updateCart,setUpdateCart]=useState(false);
  const [isLoggedIn,setIsLoggedIn] = useState();
  return (
    <PayPalScriptProvider options={{ clientId: process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID }}>
    <html lang="en">
      <body className={outfit.className}>
        <UpdateCartContext.Provider value={{updateCart,setUpdateCart,isLoggedIn,setIsLoggedIn}}>
          <Header />
          {children}
          <Toaster />
        </UpdateCartContext.Provider>

      </body>
    </html>
    </PayPalScriptProvider>
  );
}
